baseURL = "http://hugo-dukecloudcicd.s3-website.us-east-2.amazonaws.com/"
languageCode = "en-us"
title = "My New Hugo Site via AWS Cloud9"
theme = "ananke"
[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://hugo-dukecloudcicd/?region=us-east-2" #your bucket here